Repository zembutsu/docs.docker.jp, pull requests merged in 2020-10, with the labels that each got.

#305 Fix typos "Docker"
  config/daemon/daemon.rst
  develop/develop-images/image_management.rst
  develop/index.rst
  docker-for-mac/multi-arch.rst
  engine/security/rootless.rst
  sample/index.rst
Labels: bug/typo

#306 Enable docker build and publish the image for developers
  .github/workflows/docker-publish.yml
  README.md
Labels: 拡張

#308 Update build_enhancements.rst
  develop/develop-images/build_enhancements.rst
Labels: bug/typo

#309 Update image_management.rst
  develop/develop-images/image_management.rst
Labels: bug/typo

#310 Update baseimages.rst
  develop/develop-images/baseimages.rst
Labels: bug/typo

#311 Update orchestration.rst
  get-started/orchestration.rst
Labels: bug/markup

#312 Update kube-deploy.rst
  get-started/kube-deploy.rst
Labels: bug/markup

#313 Update swarm-deploy.rst
  get-started/swarm-deploy.rst
Labels: bug/typo

#314 Update pruning.rst
  config/pruning.rst
Labels: bug/typo

#315 Update formatting.rst
  config/formatting.rst
Labels: bug/typo

#316 Update daemon.rst
  config/daemon/daemon.rst
Labels: bug/typo

#317 Update daemon.rst
  config/daemon/daemon.rst
Labels: bug/typo

#318 Update systemd.rst
  config/daemon/systemd.rst
Labels: bug/typo

#319 Update prometheus.rst
  config/daemon/prometheus.rst
Labels: bug/typo

#321 Update index.rst
  config/container/logging/index.rst
Labels: bug/typo

#320 Update runmetrics.rst
  config/container/runmetrics.rst
Labels: bug/typo

#322 Update configure.rst
  config/container/logging/configure.rst
Labels: bug/markup

#323 Update gcplogs.rst
  config/container/logging/gcplogs.rst
Labels: bug/typo

#325 Update rootless.rst
  engine/security/rootless.rst
Labels: bug/typo

#326 Update add-nodes.rst
  engine/swarm/swarm-tutorial/add-nodes.rst
Labels: bug/typo

#327 Update rolling-update.rst
  engine/swarm/swarm-tutorial/rolling-update.rst
Labels: bug/typo

#328 Update ingress.rst
  engine/swarm/ingress.rst
Labels: bug/typo

#329 Update services.rst
  engine/swarm/how-swarm-mode-works/services.rst
Labels: bug/typo

#330 Update swarm-task-states.rst
  engine/swarm/how-swarm-mode-works/swarm-task-states.rst
Labels: bug/typo

#331 Update swarm-mode.rst
  engine/swarm/swarm-mode.rst
Labels: bug/typo

#333 Update part2.rst
  get-started/part2.rst
Labels: bug/typo

#334 Update part2.rst
  get-started/part2.rst
Labels: bug/typo

#335 Update part3.rst
  get-started/part3.rst
Labels: bug/typo

#338 Update docker-toolbox.rst
  docker-for-mac/docker-toolbox.rst
Labels: bug/typo

#339 Update multi-arch.rst
  docker-for-mac/multi-arch.rst
Labels: bug/typo

#340 Update search.rst
  engine/reference/commandline/search.rst
Labels: bug/typo
