Repository zembutsu/docs.docker.jp, pull requests merged in 2020-05, with the labels that each got.

#258 カスタムネットワーク作成時のMTU指定オプションの間違いを修正
  engine/reference/commandline/network_create.rst
Labels: bug/typo, doc-v17.06-beta

#257 fix typo
  engine/userguide/storagedriver/imagesandcontainers.rst
Labels: bug/typo, doc-v17.06-beta

#255 Update django.rst
  compose/django.rst
Labels: doc-v17.06-beta

#254 Update dockerrepos.rst
  engine/tutorials/dockerrepos.rst
Labels: bug/typo, doc-v17.06-beta

#256 Update extends.rst
  compose/extends.rst
Labels: bug/typo, doc-v17.06-beta

#253 Update glossary.rst
  glossary.rst
Labels: bug/typo, doc-v17.06-beta

#252 Update step_six.rst
  docker-for-mac/step_six.rst
Labels: bug/typo, doc-v17.06-beta

#251 Update step_four.rst
  docker-for-windows/step_four.rst
Labels: bug/翻訳, doc-v17.06-beta

#250 Update step_five.rst
  docker-for-mac/step_five.rst
Labels: bug/typo, doc-v17.06-beta

#249 Update step_four.rst
  docker-for-mac/step_four.rst
Labels: bug/翻訳, doc-v17.06-beta

#248 Update step_one.rst
  docker-for-mac/step_one.rst
Labels: bug/typo, doc-v17.06-beta

#247 fix typo
  compose/reference/overview.rst
Labels: bug/typo, doc-v17.06-beta

#246 fix a typo.
  docker-hub/builds.rst
Labels: bug/typo, doc-v17.06-beta

#245 Fix a typo
  engine/reference/commandline/cli.rst
Labels: bug/typo, doc-v17.06-beta

#244 Fix typo (下図→数)
  engine/reference/run.rst
Labels: bug/typo, doc-v17.06-beta

#243 dokcerとなっているTypoをdockerに修正
  engine/userguide/networking/work-with-networks.rst
Labels: bug/typo, doc-v17.06-beta

#242 。が減らした
  engine/userguide/networking/default_network/dockerlinks.rst
Labels: bug/typo, doc-v17.06-beta

#239 fix typo in get-started/part2.rst
  get-started/part2.rst
Labels: bug/typo, doc-v17.06-beta

#222 fix typo
  get-started/part2.rst
Labels: bug/typo, doc-v17.06-beta

#204 dashesの翻訳を修正する
  engine/reference/commandline/tag.rst
Labels: bug/typo, doc-v17.06-beta

#188 訳修正案 /engine/index
  engine/index.rst
Labels: bug/翻訳, doc-v17.06-beta

#187 fix typo
  engine/articles/dockerfile_best-practice.rst
Labels: bug/typo, doc-v17.06-beta

#148 Fix typo
  compose/compose-file.rst
  engine/installation/index.rst
Labels: bug/typo

#163 Install as a container の文を変更
  compose/install.rst
Labels: bug/翻訳, doc-v17.06-beta
