Repository zembutsu/docs.docker.jp, pull requests merged in 2020-06, with the labels that each got.

#178 訳チェック: /engine/installation/index
  engine/installation/index.rst
Labels: bug/翻訳

#181 訳チェック /glossary
  glossary.rst
Labels: bug/翻訳

#183 訳修正案 /compose/install
  compose/install.rst
Labels: bug/翻訳, doc-v17.06-beta

#175 part3 の訳チェック
  get-started/part3.rst
Labels: bug/翻訳, doc-v17.06-beta

#177 Part4 の訳チェック
  get-started/part4.rst
Labels: bug/翻訳, doc-v17.06-beta

#192 訳修正案 /compose/reference/up
  compose/reference/up.rst
Labels: doc-v17.06-beta

#193 訳修正案 /compose/reference/build
  compose/reference/build.rst
Labels: doc-v17.06-beta

#186 訳修正案 /engine/docker_overview
  engine/docker-overview.rst
Labels: doc-v17.06-beta

#190 訳追加案 /includes/install-script
  _includes/install-script.rst
Labels: doc-v17.06-beta

#191 訳修正案 /engine/installation/linux/docker-ce/centos
  engine/installation/linux/docker-ce/centos.rst
Labels: doc-v17.06-beta

#194 訳追記案 /engine/installation/linux/docker-ce/binaries
  engine/installation/linux/docker-ce/binaries.rst
Labels: doc-v17.06-beta

#195 訳修正案 /compose/startup-order
  compose/startup-order.rst
Labels: doc-v17.06-beta

#196 訳修正案 /engine/userguide/eng-image/baseimages
  engine/userguide/eng-image/baseimages.rst
Labels: doc-v17.06-beta

#199 訳追加案 /compose/environment-variables
  compose/environment-variables.rst
  compose/toc.rst
Labels: doc-v17.06-beta

#200 訳修正案 /machine/install-machine
  machine/install-machine.rst
Labels: doc-v17.06-beta

#201 訳修正案 /compose/django
  compose/django.rst
  compose/images/django-it-worked.png
Labels: conflict対応予定, doc-v17.06-beta

#202 訳修正案 /engine/reference/builder その１
  engine/reference/builder.rst
Labels: conflict対応予定, doc-v17.06-beta

#203 訳修正案 /engine/reference/builder その２
  engine/reference/builder.rst
Labels: doc-v17.06-beta

#205 訳修正案 /engine/reference/builder その３
  engine/reference/builder.rst
Labels: doc-v17.06-beta

#206 訳修正案 /engine/reference/builder その４
  engine/reference/builder.rst
Labels: doc-v17.06-beta

#189 訳修正案 /engine/userguide/eng-image/dockerfile_best-practices
  engine/userguide/eng-image/dockerfile_best-practices.rst
Labels: doc-v17.06-beta

#207 訳追加案 /engine/userguide/eng-image/multistage-build
  engine/userguide/eng-image/index.rst
  engine/userguide/eng-image/multistage-build.rst
Labels: doc-v17.06-beta

#208 訳追加案 /engine/swarm/configs
  engine/swarm/configs.rst
Labels: doc-v17.06-beta

#211 訳修正案 /engine/extend/plugins_volume
  engine/extend/plugins_volume.rst
Labels: doc-v17.06-beta

#214 訳修正案 /engine/tutorials/index
  engine/tutorials/index.rst
Labels: doc-v17.06-beta

#215 訳修正案 /compose/link-env-deprecated
  compose/link-env-deprecated.rst
Labels: doc-v17.06-beta

#216 訳修正案 /swarm/networking
  swarm/networking.rst
Labels: doc-v17.06-beta

#217 訳修正案 /compose/extends
  compose/extends.rst
Labels: doc-v17.06-beta

#218 訳修正案 /compose/reference/envvars
  compose/reference/envvars.rst
Labels: doc-v17.06-beta

#219 訳修正案 /compose/reference/index
  compose/reference/index.rst
Labels: doc-v17.06-beta

#234 訳修正案 /engine/userguide/networking/default_network/dockerlinks
  engine/userguide/networking/default_network/dockerlinks.rst
Labels: doc-v17.06-beta

#232 訳修正案 /engine/userguide/labels-custom-metadata
  engine/userguide/labels-custom-metadata.rst
Labels: doc-v17.06-beta

#231 訳修正案 /engine/userguide/storagedriver/imagesandcontainers
  engine/userguide/storagedriver/imagesandcontainers.rst
Labels: doc-v17.06-beta

#230 訳修正案 /docker-hub/orgs
  docker-hub/orgs.rst
Labels: doc-v17.06-beta

#229 訳修正案 /engine/breaking_changes
  engine/breaking_changes.rst
Labels: doc-v17.06-beta

#227 訳修正案 /docker-hub/official_repos
  docker-hub/images/scan-drilldown.gif
  docker-hub/official_repos.rst
Labels: doc-v17.06-beta

#226 訳修正案 /docker-hub/repos
  docker-hub/repos.rst
Labels: doc-v17.06-beta

#225 訳修正案 /compose/wordpress
  compose/wordpress.rst
Labels: doc-v17.06-beta

#223 訳追加案 /compose/bundles
  compose/bundles.rst
Labels: doc-v17.06-beta

#221 訳修正案 /compose/rails
  compose/images/rails-welcome.png
  compose/rails.rst
Labels: doc-v17.06-beta

#220 訳追加案 /compose/reference/{bundle,exec,images,push,top}
  compose/reference/bundle.rst
  compose/reference/exec.rst
  compose/reference/images.rst
  compose/reference/push.rst
  compose/reference/top.rst
Labels: doc-v17.06-beta

#155 Fix char code
  get-started/part2.rst
Labels: doc-v17.06-beta

#261 v17.06のバージョン固定と最終更新日表示
  conf.py
  index.rst
Labels: doc-v17.06-beta

#213 訳修正案 /compose/networking
  compose/networking.rst
Labels: doc-v17.06-beta

#263 Docker for Desktop のドキュメントを更新
  desktop/dashboard.rst
  desktop/opensource.rst
  desktop/toc.rst
  docker-for-mac/faq.rst
  docker-for-mac/install.rst
  docker-for-windows/docker-toolbox.rst
  docker-for-windows/edge-release-notes.rst
  docker-for-windows/faq.rst
  docker-for-windows/index.rst
  docker-for-windows/install-windows-home.rst
  docker-for-windows/install.rst
  docker-for-windows/kubernetes.rst
  docker-for-windows/last_page.rst
  docker-for-windows/networking.rst
  docker-for-windows/overview.rst
  docker-for-windows/release-notes.rst
  docker-for-windows/toc.rst
  docker-for-windows/troubleshoot.rst
  docker-for-windows/wsl.rst
Labels: doc-v20.03

#264 Fix typo
  engine/reference/commandline/dockerd.rst
Labels: bug/typo

#268 Fix wrong option.
  engine/reference/commandline/commit.rst
Labels: bug/typo
