Repository zembutsu/docs.docker.jp, pull requests merged in 2021-04, with the labels that each got.

#356 Fix typo in pruning.rst
  config/pruning.rst
Labels: bug/typo

#358 訳修正案 /engine/reference/commandline/dockerd #2
  engine/reference/commandline/dockerd.rst
Labels: bug/翻訳

#359 訳修正案 /engine/reference/commandline/dockerd #3
  engine/reference/commandline/dockerd.rst
Labels: bug/翻訳

#360 訳修正案 /engine/reference/commandline/dockerd #4
  engine/reference/commandline/dockerd.rst
Labels: bug/翻訳

#284 訳修正案 /engine/security/userns-remap
  engine/security/userns-remap.rst
Labels: conflict対応予定
