Repository zembutsu/docs.docker.jp, pull requests merged in 2023-07, with the labels that each got.

#445 Update baseimages.rst
  develop/develop-images/baseimages.rst
Labels: bug/翻訳

#446 Fix typo
  config/containers/logging/awslogs.rst
Labels: bug/翻訳

#447 Fix: Typo
  engine/reference/commandline/stack_deploy.rst
Labels: bug/markup

#448 [fix] コードブロックのインデントを調整
  compose/compose-file/index.rst
Labels: bug/markup

#449 Fix: Typo
  engine/reference/builder.rst
Labels: bug/typo

#451 Fix ruby in buildx explanation
  develop/develop-images/build_enhancements.rst
Labels: bug/markup
